apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mediso-payment-sample-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/proxy-buffer-size: 8k
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
spec:
  ingressClassName: public
  tls:
    - hosts:
        - api.medisample.online
  rules:
    - host: api.medisample.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mediso-payment-sample-api-service
                port:
                  number: 8080