kind: Service
apiVersion: v1
metadata:
  name: mediso-payment-sample-api-service
  namespace: default
  labels:
    k8s-app: mediso-payment-sample-api
spec:
  ports:
    - name: tcp-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    k8s-app: mediso-payment-sample-api
  type: ClusterIP
